### ISSUE TITLE
Bulding on Windows 10 x64

### ISSUE THREAD

**Issue by pidgeon777** [Smattr/clink#1]
Hello, first of all congratulations, this seems to be an interesting project.

I would like to test it, could you please give me some tips on how to build it on Windows 10 x64?

**Comment by Smattr** [comment]
Hi, thanks for your interest! I don't do any development on Windows, so I never built this with Windows in mind. It might be possible to get it running in Cygwin or WSL. Adding Windows support would be great, but I have no Windows machine to test on.

In terms of how to test the binary once it's built, there's no test suite in this project because I was still exploring whether some of the underlying ideas were feasible. I stopped working on this several years ago, but recently started porting it to C (in the subdirectory crewrite) to introduce some more modularity. However, the C version is still unlikely to work on Windows as I can't test this without a Window machine.

**Comment by pidgeon777** [comment]
Well, if you wish I could try to build it on Windows to see what happens.

In the meanwhile, I could try to build it using Cygwin. Do you think if any instruction is available to properly proceed with the build?

**Comment by Smattr** [comment]
To build it in Cygwin, I would guess you follow the same steps as *nix. I was about to point you to the README when I realised there are no compilation instructions there. Whoops! Just pushed a change now that adds some building steps.

If you run into problems, let me know. As I said, I don't have a Windows machine on which to debug, but if I can guess the solution I can try to form a fix.

**Comment by Smattr** [comment]
To give some (possibly relevant) update... I've been modernising and cleaning up Clink (lib/exe separation, C++17, remove GNU Readline dependency, ...). This is nowhere near close to done, but I'm hoping this will aid cross compatibility. I.e. the main difficulty will be installing LLVM/libclang, not building Clink. If there's anything obvious that would aid Windows compatibility, please let me know. My situation remains the same — no Windows box to test on — but I'm using some more contemporary abstractions like `std::filesystem` that hopefully should ease some pain.

**Comment by Smattr** [comment]
From the above history, I’m assuming compiling Clink on Cygwin worked out. Please let me know if the README steps don’t work under Cygwin/MinGW/WSL.
