### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by pidgeon777** [Smattr/clink#21]
Again, this seems to be a truly interesting project. Is it still under development?

**Comment by Smattr** [comment]
These days, not so much. Sorry I probably should have communicated this more obviously on #1, but I didn't realize anyone was still paying attention to this little project :)

Since the updates there, I ported the code base back to C, partly for better portability and partly as a reaction to discovering the relative immaturity of C++17 implementations.

I've been using Clink in the wild, but it's led me to conclude that there are some flaws in its design. Specifically:
* fully accurate C/C++ parsing can be an anti-feature. When doing development work, your code is sometimes not in a compilable state and libclang will choke on it. In this situation, Cscope's permissiveness is actually a very valuable feature.
* Clang is slow. When parsing metaprogramming-heavy template code this is a noticeable annoyance. Templates of course make no difference to Cscope because it doesn't even know what a template is.

I think the rest of Clink's feature set is desirable, but there are quite a few rough edges. In particular, if you work on macOS #6 starts becoming really annoying.

**Comment by pidgeon777** [comment]
Hi! Still considering to develop this? It has a lot of potentials and one day could possibly be considered as a substitute for `cscope`. Maybe even thanks to the help of developers which could be interested in helping out.

**Comment by Smattr** [comment]
Realistically, I won't have any time to work on this until at least mid-2021. I have some other higher priority things going on right now. PRs always welcome though :)

**Comment by pidgeon777** [comment]
If only I had the competence to do some PRs, I would happily do so! :+1: 

In the meanwhile, I'll have to patiently wait till mid-2021, then :).

**Comment by Smattr** [comment]
Well it's mid-2021 and the unthinkable has happened: I'm actually in a position to fulfill my promise. No guarantee on how fast progress will proceed, but I'm at least hacking on this again.

**Comment by pidgeon777** [comment]
This is a long-awaited, and great news.

Congratulations and the best of luck for your project!
